import { Candidate, CandidateStatus } from './entities/candidates.entity';
import { randomUUID } from 'crypto';

export const seedCandidates: Candidate[] = [
  {
    id: randomUUID(),
    name: 'John Doe',
    email: 'john@example.com',
    phone: '123456789',
    position: 'Frontend',
    status: CandidateStatus.New,
    notes: 'First candidate',
    createdAt: new Date(),
  },
  {
    id: randomUUID(),
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '987654321',
    position: 'Backend',
    status: CandidateStatus.Screening,
    notes: 'Second candidate',
    createdAt: new Date(),
  },
  {
    id: randomUUID(),
    name: 'Alice Johnson',
    email: 'alice@example.com',
    phone: '555123456',
    position: 'Designer',
    status: CandidateStatus.Interview,
    notes: 'Third candidate',
    createdAt: new Date(),
  },
  {
    id: randomUUID(),
    name: 'Bob Brown',
    email: 'bob@example.com',
    phone: '555987654',
    position: 'Frontend',
    status: CandidateStatus.Offer,
    notes: 'Fourth candidate',
    createdAt: new Date(),
  },
  {
    id: randomUUID(),
    name: 'Charlie Davis',
    email: 'charlie@example.com',
    phone: '555111222',
    position: 'Backend',
    status: CandidateStatus.Hired,
    notes: 'Fifth candidate',
    createdAt: new Date(),
  },
];
